/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Progression: (() => {
      const tableId = new TableId("", "Progression");
      return defineComponent(
        world,
        {
          player: RecsType.String,
          chapter: RecsType.BigInt,
          episode: RecsType.BigInt,
          scene: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Rule: (() => {
      const tableId = new TableId("", "Rule");
      return defineComponent(
        world,
        {
          initialized: RecsType.Boolean,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
