// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Game, GameData, GameTableId } from "./tables/Game.sol";
import { Rule, RuleTableId } from "./tables/Rule.sol";
