// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Progression, ProgressionData, ProgressionTableId } from "./tables/Progression.sol";
import { Rule, RuleTableId } from "./tables/Rule.sol";
