// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IGameSystem {
  function addColor(string memory nft, string memory content) external;

  function toggleDone(bytes32 gameId) external;
}
