// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IProgressionSystem {
  function updateProgression(address player, uint256 chapter, uint256 episode, uint256 scene) external;
}
